route:
  receiver: default
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical
      group_wait: 10s
      repeat_interval: 15m
    - matchers:
        - severity="warning"
      receiver: warning
      repeat_interval: 1h

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname"]

receivers:
  - name: default
    webhook_configs:
      - url: "http://alert-relay:9081/webhook/default"
        send_resolved: true
  - name: warning
    webhook_configs:
      - url: "http://alert-relay:9081/webhook/warning"
        send_resolved: true
  - name: critical
    webhook_configs:
      - url: "http://alert-relay:9081/webhook/critical"
        send_resolved: true
