global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/prometheus_alerts.yml

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8010"]

  - job_name: "alert-relay"
    metrics_path: /metrics
    static_configs:
      - targets: ["alert-relay:9081"]
